# Generated by Django 5.2.1 on 2025-05-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem'),
    ]

    operations = [
    ]
